# Server Port
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://mysql-324faa35-thanhhosy0606-b328.i.aivencloud.com:16658/defaultdb?useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true


# ==========================================
# Cấu hình Cổng Thanh Toán PayOS (VietQR tự động)
# ==========================================
payos.client-id=${PAYOS_CLIENT_ID:8bfb154b-bfa4-4a3c-a0be-acc4137a7e29}
payos.api-key=${PAYOS_API_KEY:d220df7f-0081-417e-93fb-0fc27e021c1c}
payos.checksum-key=${PAYOS_CHECKSUM_KEY:136724377bd329a8c170a84453d3e3c2629c4c47b053f76fc9a1c4ac4c5c1cfd}
payos.return-url=${PAYOS_RETURN_URL:https://book-store-6q2m.onrender.com/payment-result.html}
payos.cancel-url=${PAYOS_CANCEL_URL:https://book-store-6q2m.onrender.com/}


